spring:
  application:
    name: service-provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/provider_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081     #provider consumer port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      swagger-url: http://localhost:8081/swagger-ui.html

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity

logging:
  level:
    org.springframework: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html